spring.application.name=lumora-api

spring.datasource.url=jdbc:postgresql://localhost:5432/lumora
spring.datasource.username=postgres
spring.datasource.password=SantanderEYF*25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
